sudo: required
language: go
go_import_path: github.com/rupayaproject/go-rupaya

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on


jobs:
  include:

  - stage: Lint
    sudo: false
    go: '1.12.x'
    git:
      submodules: false
      script:
        - go run build/ci.go lint

  - stage: Build and test
    go: '1.12.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1
  - go: '1.11.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1

  - stage: Github release
    go: '1.11.x'
    script:
      - make tomo-cross
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file_glob: true
      file: build/bin/tomo-*
      skip_cleanup: true
      on:
        tags: true

  - stage: Build and push image
    services:
      - docker
    install: skip
    before_script:
      - docker build -t rupayaproject/go-rupaya .
      - docker build -t rupaya/node -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag rupayaproject/go-rupaya rupayaproject/go-rupaya:latest
      - docker push rupayaproject/go-rupaya:latest
      - docker tag rupayaproject/go-rupaya rupayaproject/go-rupaya:$TRAVIS_BUILD_ID
      - docker push rupayaproject/go-rupaya:$TRAVIS_BUILD_ID
      - docker tag rupaya/node rupaya/node:latest
      - docker push rupaya/node:latest
      - docker tag rupaya/node rupaya/node:$TRAVIS_BUILD_ID
      - docker push rupaya/node:$TRAVIS_BUILD_ID

  - stage: Build and push image (tagged)
    services:
      - docker
    install: skip
    before_script:
      - docker build -t rupayaproject/go-rupaya .
      - docker build -t rupayaproject/go-rupaya -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag rupayaproject/go-rupaya rupayaproject/go-rupaya:latest
      - docker push rupayaproject/go-rupaya:latest
      - docker tag rupayaproject/go-rupaya rupayaproject/go-rupaya:$TRAVIS_TAG
      - docker push rupayaproject/go-rupaya:$TRAVIS_TAG
      - docker tag rupayaproject/go-rupaya rupaya/node:latest
      - docker push rupaya/node:latest
      - docker tag rupaya/node rupaya/node:$TRAVIS_TAG
      - docker push rupaya/node:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Build and test
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupayaproject/go-rupaya
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = rupayaproject/go-rupaya
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupayaproject/go-rupaya

notifications:
  slack:
    rooms:
      secure: DoWVSWEKZre0rsYvHPqOBpYa5hL7DagVCP7eGR+2dluzsyUOTW58uiaezaZMAPPG6k7i1TC9CufONkFRwH6kqLrFtAFd+t3sKb3X4D9/PSa9k88uBuNfsX+JhUzEMT53pfLO9NTBbZs3M6bOuZDP7GddWWnMZpO6Mu7RzZtVxyqbZIcNu3nxsmLkoaQ8726npaHrxhO1Ab+3rgR4dkNFLgl9/CnPwvuv/j24dsKzly6tF+4Ms9Fz5O0Te8zK5d/UWZN50e+uDnbzcIvbY2VHOYXchXZRbfKO8/M2TIXLPKbLc3alCw1ZvpFZqiMYK3SnGNby4FLp8RlC6H4sv52YeNq3fHH8SgOJ3xTL8m6ejIlqoKnUNsJ1lwtfiEVu5D1b8FRKTPqoh+cjadJxsF9dO0xZsf1d5Pmq6Ncr0j6di1ZMjCc6TPFERxkdA48+PzQY4TqfBpM4E5RnJuX9O9MJFbA1fZo2xhHcy0LlkslZMpSwiv/YO4bCJZPmxvHtruqELJXxjYyC67UbzSzrBVE1g1bXy0V5xyxPIEA38jzlNczhq6fg2gyEc+6JCbzN2gFoAS5uFWQHpUhXHc7zNB5Jyi7GPQv6cfHYcedjn9In9/bNDqqGexGX4Ih/cb6W1GOHC7c2A/AsfTa9KWmsyj7YwBRXFIXfme7bBh6VGuRqU3Y=
    on_success: change
    on_failure: always
