sudo: required
language: go
go_import_path: github.com/rupayaproject/rupaya

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on


jobs:
  include:

  - stage: Lint
    sudo: false
    go: '1.12.x'
    git:
      submodules: false
      script:
        - go run build/ci.go lint

  - stage: Build and test
    go: '1.12.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1
  - go: '1.11.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1

  - stage: Github release
    go: '1.12.x'
    script:
      - GOARCH=amd64 GOOS=linux go build -o ./build/bin/rupaya-linux-amd64 -v ./cmd/rupaya
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file_glob: true
      file: build/bin/rupaya-*
      skip_cleanup: true
      on:
        tags: true

  - stage: Build and push image
    services:
      - docker
    install: skip
    before_script:
      - docker build -t rupayaproject/rupaya .
      - docker build -t rupaya/node -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag rupayaproject/rupaya rupayaproject/rupaya:latest
      - docker push rupayaproject/rupaya:latest
      - docker tag rupayaproject/rupaya rupayaproject/rupaya:$TRAVIS_BUILD_ID
      - docker push rupayaproject/rupaya:$TRAVIS_BUILD_ID
      - docker tag rupaya/node rupaya/node:latest
      - docker push rupaya/node:latest
      - docker tag rupaya/node rupaya/node:$TRAVIS_BUILD_ID
      - docker push rupaya/node:$TRAVIS_BUILD_ID

  - stage: Build and push image (tagged)
    services:
      - docker
    install: skip
    before_script:
      - docker build -t rupayaproject/rupaya .
      - docker build -t rupayaproject/rupaya -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag rupayaproject/rupaya rupayaproject/rupaya:latest
      - docker push rupayaproject/rupaya:latest
      - docker tag rupayaproject/rupaya rupayaproject/rupaya:$TRAVIS_TAG
      - docker push rupayaproject/rupaya:$TRAVIS_TAG
      - docker tag rupayaproject/rupaya rupaya/node:latest
      - docker push rupaya/node:latest
      - docker tag rupaya/node rupaya/node:$TRAVIS_TAG
      - docker push rupaya/node:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Build and test
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupayaproject/rupaya
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = rupayaproject/rupaya
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupayaproject/rupaya
